spring:
  application:
    name: ms-gateway
  config:
    import: "optional:configserver:http://ms-config:8888"

server:
  port: 8088   

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: "eL8Jf0uI1H1YBcvSMBjDyF4EK7TMLDNK4sC7uQslY6t8tP0vqEoL8g6avsznxYjYRXKChP5BcbM4g38c+QFhAw=="
  access-exp-seconds: 900          # 15 min
  refresh-exp-days: 30