server:
  port: 8888

spring:
  application:
    name: ms-config
  profiles:
    active: native

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs


  cloud:
    config:
      server:
        native:
          search-locations: file:///app/contracts

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh

logging:
  level:
    "[org.springframework.cloud.config]": INFO
    "[uasz.alumni]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
