server:
  port: 8888

spring:
  application:
    name: ms-config

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs


  cloud:
    config:
      server:
        git:
          uri: file:///app/contracts   # Dossier local des configurations
          default-label: main                                        # branche par défaut
          clone-on-start: true                                       # clone au démarrage
          force-pull: true                                           # récupère les dernières modifs
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh

logging:
  level:
    "[org.springframework.cloud.config]": INFO
    "[uasz.alumni]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
