spring:
  application:
    name: ms-gateway

  config:
    import: "configserver:http://ms-config:8888"   

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
