spring:
  application:
    name: ms-gateway

  config:
    import: "configserver:http://ms-config:8888"

  cloud:
    gateway:
      routes:
        - id: ms-invitation
          uri: lb://MS-INVITATION
          predicates:
            - Path=/api/v1/invitations/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
