server:
  port: 8072   # ou autre si ms-user utilise déjà 8080

spring:
  application:
    name: ms-cv-v2
  config:
    import: "configserver:http://ms-config:8888"

jwt:
  secret: "eL8Jf0uI1H1YBcvSMBjDyF4EK7TMLDNK4sC7uQslY6t8tP0vqEoL8g6avsznxYjYRXKChP5BcbM4g38c+QFhAw=="
  access-exp-seconds: 900          # 15 min
  refresh-exp-days: 30